"use strict";
exports.__esModule = true;
var vue_1 = require("vue");
var element_ui_1 = require("element-ui");
//Layout 布局隐藏
require("element-ui/lib/theme-chalk/display.css");
vue_1["default"].use(element_ui_1.Dialog);
vue_1["default"].use(element_ui_1.Upload);
vue_1["default"].use(element_ui_1.Dropdown);
vue_1["default"].use(element_ui_1.DropdownMenu);
vue_1["default"].use(element_ui_1.DropdownItem);
vue_1["default"].use(element_ui_1.Radio);
vue_1["default"].use(element_ui_1.RadioGroup);
vue_1["default"].use(element_ui_1.RadioButton);
vue_1["default"].use(element_ui_1.Checkbox);
vue_1["default"].use(element_ui_1.CheckboxButton);
vue_1["default"].use(element_ui_1.CheckboxGroup);
vue_1["default"].use(element_ui_1.Image);
vue_1["default"].use(element_ui_1.Button);
vue_1["default"].use(element_ui_1.Row);
vue_1["default"].use(element_ui_1.Col);
vue_1["default"].use(element_ui_1.Input);
vue_1["default"].use(element_ui_1.Form);
vue_1["default"].use(element_ui_1.FormItem);
vue_1["default"].use(element_ui_1.Container);
vue_1["default"].use(element_ui_1.Header);
vue_1["default"].use(element_ui_1.Aside);
vue_1["default"].use(element_ui_1.Main);
vue_1["default"].use(element_ui_1.Footer);
vue_1["default"].use(element_ui_1.Menu);
vue_1["default"].use(element_ui_1.Submenu);
vue_1["default"].use(element_ui_1.MenuItem);
vue_1["default"].use(element_ui_1.MenuItemGroup);
vue_1["default"].use(element_ui_1.Popover);
vue_1["default"].use(element_ui_1.Card);
vue_1["default"].use(element_ui_1.Breadcrumb);
vue_1["default"].use(element_ui_1.BreadcrumbItem);
vue_1["default"].use(element_ui_1.Table);
vue_1["default"].use(element_ui_1.TableColumn);
vue_1["default"].use(element_ui_1.Pagination);
vue_1["default"].use(element_ui_1.Divider);
vue_1["default"].use(element_ui_1.Backtop);
vue_1["default"].use(element_ui_1.DatePicker);
vue_1["default"].use(element_ui_1.Select);
vue_1["default"].use(element_ui_1.Option);
vue_1["default"].use(element_ui_1.Tabs);
vue_1["default"].use(element_ui_1.TabPane);
vue_1["default"].use(element_ui_1.TimePicker);
vue_1["default"].use(element_ui_1.Switch);
vue_1["default"].prototype.$message = element_ui_1.Message;
